pipeline {
    environment {
        MYSQL_ROOT_PASSWORD=CREDENTIALS("MYSQL_ROOT_PASSWORD")
    }
    agent any
    stages{
        stage"Run Script") {
            dir("Task2) {
                sh "sh deploy.sh"
            }
        }		
    }
}
